version: '3.8'

services:
  # Weaviate vector database
  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: actionrunner-weaviate
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/v1/.well-known/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - vectordb

  # Pinecone alternative - Qdrant (local vector database)
  # Note: Pinecone is a cloud service, so we provide Qdrant as a local alternative
  # for testing vector database operations similar to Pinecone
  qdrant:
    image: qdrant/qdrant:latest
    container_name: actionrunner-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - vectordb

networks:
  vectordb:
    driver: bridge

volumes:
  weaviate_data:
  qdrant_data:
