# GitHub Actions Self-Hosted Runner Configuration - DEVELOPMENT
# Template for development and testing environments

runner:
  name: "action-runner-dev"
  labels:
    - "self-hosted"
    - "Windows"
    - "X64"
    - "development"
    - "test"
  group: "Development"

paths:
  runner_home: "C:\\actions-runner-dev"
  work_directory: "C:\\actions-runner-dev\\_work"
  temp_directory: "C:\\Temp"
  log_directory: "C:\\actions-runner-dev\\logs"

resources:
  max_concurrent_jobs: 2
  cpu:
    max_cores: 4
    affinity: ""
  memory:
    max_memory_gb: 8
    reserved_memory_gb: 2
  disk:
    min_free_space_gb: 50
    auto_cleanup: true
    cleanup_per_job: true

timeouts:
  job_timeout_minutes: 180
  queue_timeout_minutes: 15
  step_timeout_minutes: 30

environment:
  system:
    DOTNET_ROOT: "C:\\Program Files\\dotnet"
    JAVA_HOME: "C:\\Program Files\\Java\\jdk-17"
    PYTHON_PATH: "C:\\Python311"
    NODE_PATH: "C:\\Program Files\\nodejs"
  runner:
    ACTIONS_RUNNER_PRINT_LOG_TO_STDOUT: "1"
    RUNNER_ALLOW_RUNASROOT: "0"
  custom: {}

docker:
  enabled: true
  socket_path: "npipe:////./pipe/docker_engine"
  isolation_mode: "process"
  container_limits:
    memory_gb: 4
    cpu_cores: 2
  auto_cleanup_containers: true
  auto_cleanup_images: true

monitoring:
  enabled: true
  health_check_interval: 600
  alert_webhook: ""
  alerts:
    runner_offline: true
    low_disk_space: true
    high_cpu_usage: false
    high_memory_usage: false
    job_failure: false
  thresholds:
    cpu_warning_percent: 90
    cpu_critical_percent: 95
    memory_warning_percent: 90
    memory_critical_percent: 95
    disk_warning_gb: 50
    disk_critical_gb: 30

security:
  firewall_enabled: false
  allowed_networks: []
  block_external_access: false
  audit_logging: false

logging:
  level: "debug"
  retention_days: 7
  max_file_size_mb: 50
  rotation_enabled: true
  console_output: true

maintenance:
  auto_update: false
  update_check_interval_hours: 168
  backup_before_update: false
  maintenance_window: ""

features:
  experimental:
    new_job_engine: true
    job_queueing: true
  disabled:
    artifact_upload: false
    cache: false
