name: Runner Health Check

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  health-check:
    name: Check Runner Health
    runs-on: [self-hosted, windows]
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run comprehensive health check
        shell: powershell
        run: |
          Write-Host "Running comprehensive health check script..."
          & .\scripts\health-check.ps1 -OutputFormat Text -DiskThresholdGB 100

      - name: Run health check with JSON output
        continue-on-error: true
        shell: powershell
        run: |
          Write-Host "`n=== JSON Health Report ===" -ForegroundColor Cyan
          $jsonOutput = & .\scripts\health-check.ps1 -OutputFormat JSON -DiskThresholdGB 100
          Write-Host $jsonOutput

          # Parse and check overall health
          $healthData = $jsonOutput | ConvertFrom-Json
          if ($healthData.OverallHealth -eq "Unhealthy") {
            Write-Error "Health check failed! Overall status: Unhealthy"
            exit 1
          } elseif ($healthData.OverallHealth -eq "Warning") {
            Write-Warning "Health check completed with warnings"
          } else {
            Write-Host "`n[SUCCESS] All health checks passed!" -ForegroundColor Green
          }

      - name: Check Docker health
        shell: powershell
        run: |
          Write-Host "`n=== Docker Health Check ===" -ForegroundColor Cyan

          # Check if Docker is running
          try {
            $dockerInfo = docker info 2>&1
            if ($LASTEXITCODE -eq 0) {
              Write-Host "[OK] Docker is running" -ForegroundColor Green
            } else {
              Write-Error "Docker is not running or not accessible"
              exit 1
            }
          } catch {
            Write-Error "Failed to check Docker status: $_"
            exit 1
          }

          # Check Docker containers
          Write-Host "`nChecking Docker containers..." -ForegroundColor Yellow
          docker ps -a --format "table {{.Names}}\t{{.Status}}\t{{.State}}"

          # Check for unhealthy containers
          $unhealthy = docker ps --filter "health=unhealthy" --format "{{.Names}}"
          if ($unhealthy) {
            Write-Error "Unhealthy containers found: $unhealthy"
            exit 1
          }

          Write-Host "`n[OK] Docker health check passed" -ForegroundColor Green

      - name: Upload health report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: health-report-${{ github.run_number }}
          path: |
            C:\actions-runner\logs\health\*.json
          retention-days: 30
          if-no-files-found: ignore
